apiVersion: v1
kind: Namespace
metadata:
  name: grokctl-scheduler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grokctl-scheduler
  namespace: grokctl-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grokctl-scheduler
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - events
      - pods/binding
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grokctl-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grokctl-scheduler
subjects:
  - kind: ServiceAccount
    name: grokctl-scheduler
    namespace: grokctl-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: grokctl-scheduler
  namespace: grokctl-scheduler
spec:
  containers:
    - name: grokctl-scheduler
      image: harpreetkaurvaya/grokctl-scheduler:1.0
      imagePullPolicy: Always
  serviceAccountName: grokctl-scheduler
  serviceAccount: grokctl-scheduler
