apiVersion: v1
kind: Namespace
metadata:
  name: grokctl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fix-node-scheduler
  namespace: grokctl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fix-node-scheduler
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - events
      - pods/binding
    verbs:
      - get
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fix-node-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fix-node-scheduler
subjects:
  - kind: ServiceAccount
    name: fix-node-scheduler
    namespace: grokctl
---
apiVersion: v1
kind: Pod
metadata:
  name: fix-node-scheduler
  namespace: grokctl
spec:
  containers:
    - name: fix-node-scheduler
      image: grokctl/fix-node-scheduler:1.0
      imagePullPolicy: Always
  serviceAccountName: fix-node-scheduler
  serviceAccount: fix-node-scheduler
